from enum import Enum


class IssueType(Enum):
    """
    A list of issue types.
    """
    def __str__(self):
        return self.name

    # Lane Issues
    INVALID_DIRECTION_OF_TRAVEL = "INVALID_DIRECTION_OF_TRAVEL"
    NON_EXISTANT_JUNCTION_REF = "NON_EXISTANT_JUNCTION_REF"
    MISSING_BOUNDARY = "MISSING_BOUNDARY"
    EMPTY_LINE = "EMPTY_LINE"
    INVALID_LINE = "INVALID_LINE"
    SELF_CROSSING_LINE = "SELF_CROSSING_LINE"
    WRONG_DIRECTION_LINE = "WRONG_DIRECTION_LINE"
    LINE_CROSSES_CENTER = "LINE_CROSSES_CENTER"

    # Junction Issues
    NO_OUTFLOW = "NO_OUTFLOW"
    SPLIT_MULTIPLE_NORMAL = "SPLIT_MULTIPLE_NORMAL"
    SPLIT_NO_SPLIT_PROPERTY = "SPLIT_NO_SPLIT_PROPERTY"
    SPLIT_NO_NORMAL = "SPLIT_NO_NORMAL"
    MERGE_MULTIPLE_NORMAL = "MERGE_MULTIPLE_NORMAL"
    MERGE_NO_MERGE_PROPERTY = "MERGE_NO_MERGE_PROPERTY"
    MERGE_NO_NORMAL = "MERGE_NO_NORMAL"
    FROM_SPLIT_MISSING_PROPERTY = "FROM_SPLIT_MISSING_PROPERTY"
    MERGING_MISSING_PROPERTY = "MERGING_MISSING_PROPERTY"
    JUNCTION_TOO_FAR = "JUNCTION_TOO_FAR"
    SPLIT_RAMP_NO_NORMAL = "SPLIT_RAMP_NO_NORMAL"
    SPLIT_RAMP_MULTIPLE_NORMAL = "SPLIT_RAMP_MULTIPLE_NORMAL"

    # Lane Group Issues
    NO_LANES_IN_LANE_GROUP = "NO_LANES_IN_LANE_GROUP"
