from enum import Enum


class MapType(Enum):
    LANE = "LANE"
    LANE_ANNOTATION = "LANE_ANNOTATION"
    ROAD = "ROAD"
    MAP_READER = "MAP_READER"
    FREE_SPACE = "FREE_SPACE"
    RADAR_ZONE = "RADAR_ZONE"
    LOCALIZATION_ZONE = "LOCALIZATION_ZONE"
    DISENGAGE_ZONE = "DISENGAGE_ZONE"
    LIDAR_LINE = "LIDAR_LINE"
    LANE_PREFERENCE = "LANE_PREFERENCE"

